version: "3"

services:
  prom-server:
    image: prom/prometheus
    ports:
      - 9091:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    ports:
      - "3001:3000"     
