apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 1 # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
        - name: hotstar
          image: naveen90234/hotstar:25
          imagePullPolicy: Always # Always pull the latest image
          ports:
            - containerPort: 3000 # Port your application listens on
